[build]
  command = "npm run build" # The command to build your project
  publish = "dist"          # The directory to publish to Netlify

# Redirect all requests to index.html for single-page application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
